// swift-tools-version: 6.2
import PackageDescription

// Domain modules of the native app. Targets are added as their phase tasks begin
// (see docs/MAC_NATIVE_V2_PLAN.md, ADR-7).
let package = Package(
    name: "AletheKit",
    defaultLocalization: "en",
    platforms: [.macOS(.v26)],
    products: [
        .library(name: "AletheFoundation", targets: ["AletheFoundation"]),
        .library(name: "AletheDesign", targets: ["AletheDesign"]),
        .library(name: "AletheTerminal", targets: ["AletheTerminal"]),
        .library(name: "AletheModel", targets: ["AletheModel"]),
        .library(name: "AletheAgents", targets: ["AletheAgents"]),
    ],
    dependencies: [
        // Generated by Vendor/ghostty/build.sh (libghostty + libghostty-spm's Swift wrapper).
        .package(path: "../../Vendor/GhosttyKit"),
    ],
    targets: [
        .target(name: "AletheFoundation"),
        .target(
            name: "AletheDesign",
            resources: [.copy("Resources/Themes"), .copy("Resources/Fonts")]
        ),
        .target(name: "AletheModel", dependencies: ["AletheFoundation"]),
        .target(name: "AletheAgents"),
        .target(name: "CAlethePTY"),
        .target(
            name: "AletheTerminal",
            dependencies: [
                "AletheDesign",
                "CAlethePTY",
                .product(name: "GhosttyTerminal", package: "GhosttyKit"),
            ]
        ),
        .testTarget(name: "AletheFoundationTests", dependencies: ["AletheFoundation"]),
        .testTarget(name: "AletheDesignTests", dependencies: ["AletheDesign"]),
        .testTarget(name: "AletheTerminalTests", dependencies: ["AletheTerminal"]),
        .testTarget(name: "AletheModelTests", dependencies: ["AletheModel"]),
        .testTarget(name: "AletheAgentsTests", dependencies: ["AletheAgents"]),
    ]
)
