// swift-tools-version: 6.2
import PackageDescription

// Domain modules of the native app. Targets are added as their phase tasks begin
// (see docs/MAC_NATIVE_V2_PLAN.md, ADR-7).
let package = Package(
    name: "AletheKit",
    defaultLocalization: "en",
    platforms: [.macOS(.v26)],
    products: [
        .library(name: "AletheFoundation", targets: ["AletheFoundation"]),
        .library(name: "AletheDesign", targets: ["AletheDesign"]),
        .library(name: "AletheTerminal", targets: ["AletheTerminal"]),
        .library(name: "AletheModel", targets: ["AletheModel"]),
        .library(name: "AletheAgents", targets: ["AletheAgents"]),
        .library(name: "AletheDocuments", targets: ["AletheDocuments"]),
        .library(name: "AlethePluginKit", targets: ["AlethePluginKit"]),
        .library(name: "AletheGit", targets: ["AletheGit"]),
        .library(name: "AletheThemePack", targets: ["AletheThemePack"]),
        .library(name: "AletheMerge", targets: ["AletheMerge"]),
    ],
    dependencies: [
        // Generated by Vendor/ghostty/build.sh (libghostty + libghostty-spm's Swift wrapper).
        .package(path: "../../Vendor/GhosttyKit"),
        // Markdown parsing for the Markdown pane (ADR-11): Apple's cmark-gfm wrapper, Apache-2.0.
        .package(url: "https://github.com/swiftlang/swift-markdown.git", exact: "0.9.0"),
    ],
    targets: [
        .target(name: "AletheFoundation"),
        .target(
            name: "AletheDesign",
            resources: [.copy("Resources/Themes"), .copy("Resources/Fonts")]
        ),
        .target(name: "AletheModel", dependencies: ["AletheFoundation"]),
        .target(name: "AletheAgents"),
        .target(name: "AletheDocuments", dependencies: [.product(name: "Markdown", package: "swift-markdown")]),
        .target(name: "AlethePluginKit", dependencies: ["AletheFoundation"]),
        .target(name: "AletheGit"),
        .target(
            name: "AletheThemePack",
            dependencies: ["AlethePluginKit", "AletheDesign"],
            resources: [.copy("Resources/Themes")]
        ),
        .target(name: "AletheMerge", dependencies: ["AletheGit"]),
        .target(name: "CAlethePTY"),
        .target(
            name: "AletheTerminal",
            dependencies: [
                "AletheDesign",
                "CAlethePTY",
                .product(name: "GhosttyTerminal", package: "GhosttyKit"),
            ]
        ),
        .testTarget(name: "AletheFoundationTests", dependencies: ["AletheFoundation"]),
        .testTarget(name: "AletheDesignTests", dependencies: ["AletheDesign"]),
        .testTarget(name: "AletheTerminalTests", dependencies: ["AletheTerminal"]),
        .testTarget(name: "AletheModelTests", dependencies: ["AletheModel"], resources: [.copy("Fixtures")]),
        .testTarget(name: "AletheAgentsTests", dependencies: ["AletheAgents"]),
        .testTarget(name: "AletheDocumentsTests", dependencies: ["AletheDocuments"]),
        .testTarget(name: "AlethePluginKitTests", dependencies: ["AlethePluginKit"]),
        .testTarget(name: "AletheGitTests", dependencies: ["AletheGit"]),
        .testTarget(name: "AletheThemePackTests", dependencies: ["AletheThemePack", "AletheDesign", "AlethePluginKit"]),
        .testTarget(name: "AletheMergeTests", dependencies: ["AletheMerge", "AletheGit"]),
    ]
)
