// swift-tools-version: 6.2
import PackageDescription

// Domain modules of the native app. Targets are added as their phase tasks begin
// (see docs/MAC_NATIVE_V2_PLAN.md, ADR-7).
let package = Package(
    name: "AletheKit",
    defaultLocalization: "en",
    platforms: [.macOS(.v26)],
    products: [
        .library(name: "AletheFoundation", targets: ["AletheFoundation"]),
        .library(name: "AletheDesign", targets: ["AletheDesign"]),
        .library(name: "AletheTerminal", targets: ["AletheTerminal"]),
        .library(name: "AletheModel", targets: ["AletheModel"]),
        .library(name: "AletheAgents", targets: ["AletheAgents"]),
        .library(name: "AletheDocuments", targets: ["AletheDocuments"]),
        .library(name: "AlethePluginKit", targets: ["AlethePluginKit"]),
        .library(name: "AletheGit", targets: ["AletheGit"]),
        .library(name: "AletheThemePack", targets: ["AletheThemePack"]),
        .library(name: "AletheMerge", targets: ["AletheMerge"]),
        .library(name: "AletheTodos", targets: ["AletheTodos"]),
        .library(name: "AletheGitControl", targets: ["AletheGitControl"]),
        .library(name: "AletheFiles", targets: ["AletheFiles"]),
        .library(name: "AletheExtensionHost", targets: ["AletheExtensionHost"]),
        .library(name: "AletheExtensionSDK", targets: ["AletheExtensionSDK"]),
        .library(name: "AletheIntegrations", targets: ["AletheIntegrations"]),
        .library(name: "AletheOrchestrator", targets: ["AletheOrchestrator"]),
        .library(name: "AletheRemote", targets: ["AletheRemote"]),
        // The orchestrator's stdio MCP server (P6-10), embedded in the app under Contents/Helpers.
        .executable(name: "alethe-orchestrator-mcp", targets: ["alethe-orchestrator-mcp"]),
    ],
    dependencies: [
        // Generated by Vendor/ghostty/build.sh (libghostty + libghostty-spm's Swift wrapper).
        .package(path: "../../Vendor/GhosttyKit"),
        // Markdown parsing for the Markdown pane (ADR-11): Apple's cmark-gfm wrapper, Apache-2.0.
        .package(url: "https://github.com/swiftlang/swift-markdown.git", exact: "0.9.0"),
    ],
    targets: [
        .target(name: "AletheFoundation"),
        .target(
            name: "AletheDesign",
            resources: [.copy("Resources/Themes"), .copy("Resources/Fonts")]
        ),
        .target(name: "AletheModel", dependencies: ["AletheFoundation"]),
        .target(name: "AletheAgents"),
        .target(name: "AletheDocuments", dependencies: [.product(name: "Markdown", package: "swift-markdown")]),
        .target(name: "AlethePluginKit", dependencies: ["AletheFoundation"]),
        .target(name: "AletheGit"),
        .target(
            name: "AletheThemePack",
            dependencies: ["AlethePluginKit", "AletheDesign"],
            resources: [.copy("Resources/Themes")]
        ),
        .target(name: "AletheMerge", dependencies: ["AletheGit"]),
        .target(name: "AletheTodos", dependencies: ["AlethePluginKit", "AletheFoundation"]),
        .target(name: "AletheGitControl", dependencies: ["AlethePluginKit", "AletheGit"]),
        .target(name: "AletheFiles", dependencies: ["AletheGit"]),
        .target(name: "AletheExtensionSDK"),
        .target(name: "AletheExtensionHost", dependencies: ["AlethePluginKit", "AletheFoundation", "AletheExtensionSDK"]),
        .target(
            name: "AletheIntegrations",
            dependencies: ["AletheFoundation", "AletheGit", "AletheAgents"],
            resources: [.copy("Resources/OpenCodePlugins")]
        ),
        .target(
            name: "AletheOrchestrator",
            dependencies: ["AletheFoundation", "AletheGit", "AletheAgents", "AletheIntegrations"],
            resources: [.copy("Resources/orchestrator-tools.json")]
        ),
        .executableTarget(name: "alethe-orchestrator-mcp", dependencies: ["AletheOrchestrator"]),
        // Remote control's hub, protocol types and (from P7-7) transport; no UI.
        .target(name: "AletheRemote", dependencies: ["AletheFoundation"]),
        .target(name: "CAlethePTY"),
        .target(
            name: "AletheTerminal",
            dependencies: [
                "AletheDesign",
                "CAlethePTY",
                .product(name: "GhosttyTerminal", package: "GhosttyKit"),
            ]
        ),
        .testTarget(name: "AletheFoundationTests", dependencies: ["AletheFoundation"], resources: [.copy("Fixtures")]),
        .testTarget(name: "AletheDesignTests", dependencies: ["AletheDesign"]),
        .testTarget(name: "AletheTerminalTests", dependencies: ["AletheTerminal"]),
        .testTarget(name: "AletheModelTests", dependencies: ["AletheModel"], resources: [.copy("Fixtures")]),
        .testTarget(name: "AletheAgentsTests", dependencies: ["AletheAgents"]),
        .testTarget(name: "AletheDocumentsTests", dependencies: ["AletheDocuments"]),
        .testTarget(name: "AlethePluginKitTests", dependencies: ["AlethePluginKit"]),
        .testTarget(name: "AletheGitTests", dependencies: ["AletheGit"]),
        .testTarget(name: "AletheThemePackTests", dependencies: ["AletheThemePack", "AletheDesign", "AlethePluginKit"]),
        .testTarget(name: "AletheMergeTests", dependencies: ["AletheMerge", "AletheGit"]),
        .testTarget(name: "AletheTodosTests", dependencies: ["AletheTodos", "AlethePluginKit"]),
        .testTarget(name: "AletheGitControlTests", dependencies: ["AletheGitControl", "AletheGit", "AlethePluginKit"]),
        .testTarget(name: "AletheFilesTests", dependencies: ["AletheFiles", "AletheGit"]),
        .testTarget(
            name: "AletheIntegrationsTests",
            dependencies: ["AletheIntegrations", "AletheFoundation", "AletheGit", "AletheAgents"],
            resources: [.copy("Fixtures")]
        ),
        .testTarget(
            name: "AletheOrchestratorTests",
            dependencies: ["AletheOrchestrator", "AletheIntegrations", "AletheGit", "AletheAgents"],
            resources: [.copy("Fixtures")]
        ),
        .testTarget(name: "AletheRemoteTests", dependencies: ["AletheRemote"]),
        .testTarget(name: "AletheExtensionHostTests", dependencies: ["AletheExtensionHost", "AlethePluginKit", "AletheExtensionSDK"]),
    ]
)
