/// Semantic color tokens. Converted once from the Tauri app's `theme.css` (P0-3);
/// this file is now the source of truth.
public enum ThemeToken: String, CaseIterable, Codable, Sendable {
    case accent
    case accentBgSoft
    case accentBorder
    case accentBorderSoft
    case accentFaint
    case accentOn
    case accentRing
    case accentSoft
    case accentStrong
    case agentAntigravity
    case agentAntigravitySoft
    case agentClaude
    case agentClaudeSoft
    case agentCodex
    case agentCodexSoft
    case agentCursor
    case agentCursorSoft
    case agentFreebuff
    case agentFreebuffSoft
    case agentKiro
    case agentKiroSoft
    case agentMimo
    case agentMimoSoft
    case agentOpencode
    case agentOpencodeSoft
    case agentShell
    case agentShellSoft
    case bg
    case bgElevated
    case bgSunken
    case border
    case borderAccent
    case borderStrong
    case borderSubtle
    case fg
    case fgFaint
    case fgMuted
    case focusRing
    case panel
    case panelHover
    case projectBlack
    case projectBlue
    case projectGray
    case projectGreen
    case projectOrange
    case projectPink
    case projectPurple
    case projectRed
    case projectTeal
    case projectYellow
    case shapeTabsLaneBg
    case shapeTabsLaneBorder
    case statusActive
    case statusDisabled
    case statusIdle
    case statusOffline
    case statusOfflineSoft
    case statusStopped
    case statusStoppedSoft
    case statusWaiting
    case statusWaitingSoft
    case statusWorking
    case statusWorkingSoft
    case surfaceCardDefault
    case surfaceCardDefaultStrong
    case surfaceCardSelected
    case surfaceModal
    case textPrimary
    case textQuaternary
    case textSecondary
    case textTertiary
}
