import Foundation

/// Where Claude Code subagents are installed: a project's `.claude/agents` or `~/.claude/agents`.
public enum AgentLibraryScope: Hashable, Sendable {
    /// The project folder.
    case project(URL)
    /// The user's home folder.
    case user(home: URL)

    public var agentsDirectory: URL {
        let root = switch self {
        case .project(let folder): folder
        case .user(let home): home
        }
        return root.appending(path: ".claude", directoryHint: .isDirectory)
            .appending(path: "agents", directoryHint: .isDirectory)
    }

    /// `<profile>/config-backups/claude-agents_project/` or `claude-agents_user/`.
    public var backupSlot: ConfigBackupSlot {
        switch self {
        case .project: ConfigBackupSlot(agent: "claude", kind: "agents_project")
        case .user: ConfigBackupSlot(agent: "claude", kind: "agents_user")
        }
    }
}

/// Upstream `AgentTemplate.category` (`orquestra`, `front`, `back`, `qa`, `docs`, `economia`).
public enum AgentCategory: String, CaseIterable, Sendable {
    case orchestration, frontend, backend, qa, docs, economy
}

/// Upstream cost badge (`barato`, `medio`, `caro`): the relative spend of running the agent.
public enum AgentCost: String, CaseIterable, Sendable {
    case cheap, medium, expensive
}

/// A Claude Code subagent Alethe can install as `<name>.md`.
public struct AgentTemplate: Identifiable, Hashable, Sendable {
    public let name: String
    public let category: AgentCategory
    public let cost: AgentCost
    /// English; the app shows a localized summary keyed by `name`.
    public let summary: String
    /// The full Markdown file, frontmatter and marker included.
    public let content: String

    public var id: String { name }
    public var fileName: String { "\(name).md" }

    public init(name: String, category: AgentCategory, cost: AgentCost, summary: String, content: String) {
        self.name = name
        self.category = category
        self.cost = cost
        self.summary = summary
        self.content = content
    }
}

/// The comments that mark a file as Alethe's, so it can be removed without asking.
public enum AletheAgentMarker {
    public static let library = "<!-- generated by Alethe (library) — safe to delete -->"
    public static let economy = "<!-- generated by Alethe (economy mode) — safe to delete -->"
    /// The new English wording and the Tauri app's (`gerado pelo Alethe`, upstream `MARKER`).
    public static let phrases = ["generated by Alethe", "gerado pelo Alethe"]

    public static func isAletheGenerated(_ text: String) -> Bool {
        phrases.contains { text.contains($0) }
    }
}

/// An agent file found in a scope's `.claude/agents`.
public struct InstalledAgent: Identifiable, Hashable, Sendable {
    public let name: String
    public let url: URL
    /// Carries the Alethe marker: removable without asking.
    public let fromAlethe: Bool

    public var id: String { name }

    public init(name: String, url: URL, fromAlethe: Bool) {
        self.name = name
        self.url = url
        self.fromAlethe = fromAlethe
    }
}
